use featherfly_plugin_sdk::metadata::{
    ARCHITECTURE, BUILD_AND_INSTALL, CAPABILITIES, CONFIG_HOOK_DOCS, EVENT_DOCS,
    FULL_PLUGIN_EXAMPLE, HOST_API, HTTP_METHODS, JSON_HOOK_DOCS, LIFECYCLE, MACROS, OVERVIEW,
    REQUEST_HOOK_DOCS, REQUEST_PIPELINE, RETURN_CODES, ROUTE_HOOK_DOCS, SOURCE_TREE, TERMINOLOGY,
    plugin_api_version,
};
use std::fmt::Write as _;
use std::path::Path;

/// Plain-text plugin reference for plugin authors — every hook, event, macro, and return code.
pub fn write_plugins_reference(output: &Path) -> std::io::Result<()> {
    let mut out = String::new();
    let version = plugin_api_version();

    let _ = writeln!(out, "{}", "=".repeat(78));
    let _ = writeln!(
        out,
        "FEATHERFLY PLUGIN REFERENCE — API v{version} (native .so plugins)"
    );
    let _ = writeln!(out, "{}", "=".repeat(78));
    let _ = writeln!(
        out,
        "Auto-generated by `make docs`. HTML version: docs/plugins/index.html"
    );
    let _ = writeln!(
        out,
        "Plugins hook into FeatherFly via lifecycle events, config/request/JSON mixins, and routes."
    );
    let _ = writeln!(out);

    section(&mut out, "OVERVIEW", OVERVIEW);
    section(&mut out, "TERMINOLOGY", TERMINOLOGY);
    section(&mut out, "ARCHITECTURE", ARCHITECTURE);
    section(&mut out, "LIFECYCLE PIPELINE", LIFECYCLE);
    section(&mut out, "HTTP REQUEST PIPELINE", REQUEST_PIPELINE);
    section(&mut out, "HOST API", HOST_API);
    section(&mut out, "BUILD AND INSTALL", BUILD_AND_INSTALL);
    section(&mut out, "RETURN CODES", RETURN_CODES);
    section(&mut out, "SOURCE TREE", SOURCE_TREE);

    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "MACROS");
    let _ = writeln!(out, "{}", "-".repeat(78));
    for (name, desc) in MACROS {
        let _ = writeln!(out, "  {name}");
        let _ = writeln!(out, "    {desc}");
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "HTTP METHODS (route.register)");
    let _ = writeln!(out, "{}", "-".repeat(78));
    for (name, id) in HTTP_METHODS {
        let _ = writeln!(out, "  {name} = {id}");
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(
        out,
        "LIFECYCLE EVENTS — {} hook points (hook!(host, PluginEvent::..., handler))",
        EVENT_DOCS.len()
    );
    let _ = writeln!(out, "{}", "-".repeat(78));
    for doc in EVENT_DOCS {
        let _ = writeln!(out);
        let _ = writeln!(out, "[{}] id={}", doc.name, doc.event.as_u32());
        let _ = writeln!(out, "  Summary:    {}", doc.summary);
        let _ = writeln!(out, "  When:       {}", doc.when);
        let _ = writeln!(out, "  Payload:    {}", doc.payload);
        let _ = writeln!(
            out,
            "  Cancelable: {}",
            if doc.cancelable { "yes" } else { "no" }
        );
        let _ = writeln!(out, "  Details:    {}", doc.details);
        if !doc.use_cases.is_empty() {
            let _ = writeln!(out, "  Use cases:");
            for uc in doc.use_cases {
                let _ = writeln!(out, "    - {uc}");
            }
        }
        let _ = writeln!(out, "  Register:   {}", doc.register_example);
    }

    write_hook_guides(&mut out, "CONFIG HOOKS", CONFIG_HOOK_DOCS);
    write_hook_guides(&mut out, "REQUEST HOOKS", REQUEST_HOOK_DOCS);
    write_hook_guides(&mut out, "ROUTE HOOKS", ROUTE_HOOK_DOCS);

    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "JSON HOOKS");
    let _ = writeln!(out, "{}", "-".repeat(78));
    for doc in JSON_HOOK_DOCS {
        let _ = writeln!(out);
        let _ = writeln!(out, "[{}]", doc.name);
        let _ = writeln!(out, "  Summary:  {}", doc.summary);
        let _ = writeln!(out, "  Input:    {}", doc.input);
        let _ = writeln!(out, "  Pipeline: {}", doc.pipeline);
        let _ = writeln!(out, "  Routes:   {}", doc.route_matching);
        let _ = writeln!(out, "  Details:  {}", doc.details);
        let _ = writeln!(out, "  Register: {}", doc.register_example);
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "CAPABILITIES");
    let _ = writeln!(out, "{}", "-".repeat(78));
    for cap in CAPABILITIES {
        let _ = writeln!(out, "  - {cap}");
    }

    let _ = writeln!(out);
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "FULL EXAMPLE PLUGIN (all hook types)");
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "{FULL_PLUGIN_EXAMPLE}");

    let _ = writeln!(out);
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "QUICK EVENT INDEX");
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "  {:>3}  EVENT NAME", "ID");
    for doc in EVENT_DOCS {
        let _ = writeln!(out, "  {:>3}  {}", doc.event.as_u32(), doc.name);
    }

    std::fs::write(output, out)
}

fn section(out: &mut String, title: &str, body: &str) {
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "{title}");
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "{body}");
    let _ = writeln!(out);
}

fn write_hook_guides(
    out: &mut String,
    title: &str,
    docs: &[featherfly_plugin_sdk::metadata::HookGuideDoc],
) {
    let _ = writeln!(out, "{}", "-".repeat(78));
    let _ = writeln!(out, "{title}");
    let _ = writeln!(out, "{}", "-".repeat(78));
    for doc in docs {
        let _ = writeln!(out);
        let _ = writeln!(out, "[{}]", doc.name);
        let _ = writeln!(out, "  Summary:  {}", doc.summary);
        let _ = writeln!(out, "  When:     {}", doc.when);
        let _ = writeln!(out, "  Input:    {}", doc.input);
        let _ = writeln!(out, "  Output:   {}", doc.output);
        let _ = writeln!(out, "  Pipeline: {}", doc.pipeline);
        let _ = writeln!(out, "  Routes:   {}", doc.route_matching);
        let _ = writeln!(out, "  Source:   {}", doc.source_path);
        let _ = writeln!(out, "  Register: {}", doc.register_example);
    }
    let _ = writeln!(out);
}

#[cfg(test)]
mod tests {
    use super::*;
    use featherfly_plugin_sdk::metadata::EVENT_DOCS;
    use tempfile::TempDir;

    #[test]
    fn plugins_reference_documents_every_hook() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("plugins-reference.txt");
        write_plugins_reference(&path).unwrap();
        let text = std::fs::read_to_string(&path).unwrap();

        assert!(text.contains("FEATHERFLY PLUGIN REFERENCE"));
        assert!(text.contains("config.mutate"));
        assert!(text.contains("json.response"));

        for doc in EVENT_DOCS {
            assert!(
                text.contains(doc.name),
                "plugins-reference.txt missing `{}`",
                doc.name
            );
        }
    }
}
