use crate::routes::State;

pub fn router(state: &State) -> axum::Router<State> {
    axum::Router::new()
        .route(
            "/",
            axum::routing::get(crate::controllers::system::cloudpanel::get),
        )
        .route(
            "/site/static",
            axum::routing::post(crate::controllers::system::cloudpanel::add_static_site),
        )
        .route(
            "/site/nodejs",
            axum::routing::post(crate::controllers::system::cloudpanel::add_nodejs_site),
        )
        .route(
            "/site/python",
            axum::routing::post(crate::controllers::system::cloudpanel::add_python_site),
        )
        .route(
            "/site/reverseproxy",
            axum::routing::post(crate::controllers::system::cloudpanel::add_reverse_proxy_site),
        )
        .route(
            "/site/php",
            axum::routing::post(crate::controllers::system::cloudpanel::add_php_site),
        )
        .route(
            "/site/{domain_name}",
            axum::routing::delete(crate::controllers::system::cloudpanel::delete_site),
        )
        .route(
            "/db/master-credentials",
            axum::routing::get(crate::controllers::system::cloudpanel::get_master_credentials),
        )
        .route(
            "/db",
            axum::routing::post(crate::controllers::system::cloudpanel::add_database),
        )
        .route(
            "/db/{database_name}",
            axum::routing::delete(crate::controllers::system::cloudpanel::delete_database),
        )
        .route(
            "/db/{database_name}/export",
            axum::routing::post(crate::controllers::system::cloudpanel::export_database),
        )
        .route(
            "/user",
            axum::routing::get(crate::controllers::system::cloudpanel::list_users),
        )
        .route(
            "/user/{username}/resetpassword",
            axum::routing::put(crate::controllers::system::cloudpanel::reset_user_password),
        )
        .route(
            "/user/{username}/mfa",
            axum::routing::put(crate::controllers::system::cloudpanel::disable_user_mfa),
        )
        .route(
            "/letsencrypt/install/certificate",
            axum::routing::post(
                crate::controllers::system::cloudpanel::install_lets_encrypt_certificate,
            ),
        )
        .route(
            "/vhosttemplates",
            axum::routing::get(crate::controllers::system::cloudpanel::get_vhost_templates)
                .post(crate::controllers::system::cloudpanel::import_vhost_templates),
        )
        .route(
            "/vhosttemplate/{name}",
            axum::routing::get(crate::controllers::system::cloudpanel::view_vhost_template),
        )
        .with_state(state.clone())
}
